spt-linux-additions: Update v2025.1-2.1 - Add 'user/profiles' to user config list - Reduce default sleep time to 2 seconds - Add m_success function - Restructure a bunch of log messages - Fix m_cp to fail if the source path contains an empty directory - Improve error logging in m_extract - Improve setter functions & error handling for prefix and SPT paths - Fix issues causing SPT Patcher files sometimes not being removed correctly - Fix backup and restore functionality after a recent update broke it - bump version

diff --git a/installers/spt-linux-additions b/installers/spt-linux-additions
--- a/installers/spt-linux-additions
+++ b/installers/spt-linux-additions
@@ -37,7 +37,7 @@
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
 
 TITLE="spt-linux-additions"
-VERSION="2025.1-2"
+VERSION="2025.1-2.1"
 
 # ANSI codes
 readonly BOLD="\e[1m"; readonly UNDERLINE="\e[2m"; readonly RESET="\e[0m"
@@ -51,8 +51,8 @@ readonly BINARIES_PATH="${CACHE_PATH}/binaries"
 readonly LOG_PATH="${CACHE_PATH}/spt-linux-additions.log"
 
 # Script variables
-readonly SCRIPT_ROOT_PATH="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
 readonly SCRIPT_UPDATE_URL="https://raw.githubusercontent.com/MadByteDE/SPT-Linux-Guide/refs/heads/main/installers/spt-linux-additions"
+readonly SCRIPT_ROOT_PATH="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
 
 # Mod variables
 readonly MOD_RELEASE_JSON_URL="https://spt-releases.modd.in/release.json"
@@ -66,12 +66,10 @@ readonly PATCHER_FILE_PATH="${CACHE_PATH}/Patcher.7z"
 
 # SPT variables
 readonly SPT_USER_DATA_DIRS=("user" "BepInEx/config" "BepInEx/plugins" "BepInEx/patchers")
-readonly SPT_USER_CONFIG_DIRS=("user/sptSettings" "user/launcher" "BepInEx/config")
+readonly SPT_USER_CONFIG_DIRS=("user/sptSettings" "user/profiles" "user/launcher" "BepInEx/config")
+readonly SPT_DEFAULT_INSTALL_PATH=${SPT_INSTALL_PATH:-"drive_c/SPTarkov"}
+readonly SPT_DEFAULT_BACKUP_PATH=${SPT_BACKUP_PATH:-"drive_c/spt-backups"}
 readonly SPT_LATEST_BACKUP_FILE="${CACHE_PATH%/}/latest_backup"
-SPT_RELATIVE_INSTALL_PATH="drive_c/SPTarkov"
-SPT_RELATIVE_ROOT_BACKUP_PATH="drive_c/spt-backups"
-SPT_INSTALL_PATH="${PREFIX_PATH%/}/${SPT_RELATIVE_INSTALL_PATH%/}"
-SPT_ROOT_BACKUP_PATH="${PREFIX_PATH%/}/${SPT_RELATIVE_ROOT_BACKUP_PATH}"
 
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
@@ -95,7 +93,7 @@ m_echo() {
 
 
 m_sleep() {
-    local sleep_time=${1:-3}
+    local sleep_time=${1:-2}
     [[ ${NO_WAIT} -eq 0 ]] && sleep "${sleep_time}"
 }
 
@@ -129,8 +127,13 @@ m_msg() {
 }
 
 
+m_success() {
+    m_echo "${FUNCNAME[1]}: ${BOLD}${BLUE}$*${RESET}"
+}
+
+
 m_warn() {
-    m_echo "${BOLD}m_warn: ${YELLOW}${FUNCNAME[1]}: $*${RESET}"
+    m_echo "${FUNCNAME[1]}: ${BOLD}${YELLOW}$*${RESET}"
 }
 
 
@@ -142,7 +145,7 @@ m_dbg() {
 
 m_err() {
     local status=${2:-1}
-    m_echo "${BOLD}${RED}ERROR: ${FUNCNAME[1]}: $1 (⊙＿⊙')${RESET}"
+    m_echo "ERROR: ${FUNCNAME[1]}: ${BOLD}${RED}$1 (⊙＿⊙')${RESET}"
     m_exit "${status}"
 }
 
@@ -166,11 +169,11 @@ m_cp() {
     || m_err "Target '${target_path}' is not inside the prefix directory"
 
     # Create dir(s) & copy to new location
-    # FIXME: This probably leads to false positives if the directory already exists
-    mkdir -p "${target_path}" 1>/dev/null \
-    || m_err "Failed to create directories for target '${target_path}'"
-    cp --reflink=auto -r "${source_path}"* "${target_path}" \
-    || m_err "Failed to copy files to target directory"
+    mkdir -p "${target_path}" 1>/dev/null || m_err "Failed to create directory in '${target_path}'"
+    if ! [[ -z "$( ls -A "${source_path}" )" ]]; then
+        cp --reflink=auto -r "${source_path}"* "${target_path}" \
+        || m_err "Failed to copy files to '${target_path}'"
+    fi
 }
 
 
@@ -229,7 +232,7 @@ m_download() {
     m_run curl -f -L --connect-timeout 60 --max-redirs $max_redirs --create-dirs $url -o "${output_path}"
 
     case "$?" in
-        0) m_msg "${BLUE}Downloaded '${filename}' successfully${RESET}" ;;
+        0) m_success "Downloaded '${filename}' successfully" ;;
         *) m_warn "Failed to download '${filename}'"; return 1 ;;
     esac
 }
@@ -239,12 +242,12 @@ m_extract() {
     local archive_path="${1}"
     local target_path="${2}"
     local filename="${archive_path##*/}"
-    m_msg "Extracting '${filename}' to '${target_path}'"
-    m_run 7z x "${archive_path}" -o"${target_path}" 1>/dev/null
+    m_msg "Extracting '${filename}'"
+    m_run 7z x "${archive_path}" -o"${target_path}" 1>/dev/null || >&2
 
     case "$?" in
-        0) m_msg "${BLUE}Extracted '${filename}' successfully${RESET}" ;; 
-        *) m_err "Failed to extract '${filename}' - Error code ${status}" ;;
+        0) m_success "Extracted '${filename}' successfully" ;; 
+        *) m_err "Failed to extract '${filename}' - Error code ${$?}" ;;
     esac
 }
 
@@ -423,14 +426,14 @@ check_hash() {
     fi
     
     # Success
-    m_msg "${BOLD}${BLUE}OK${RESET}"
+    m_success "OK"
 }
 
 
 check_flatpak_env() {
     # Check for flatpak env
     if [ ${FLATPAK_SANDBOX_DIR} ]; then
-        m_msg "${YELLOW}Flatpak environment detected!${RESET}"
+        m_echo "${BOLD}${YELLOW}Flatpak environment detected!${RESET}"
         m_echo
         m_echo "    > It looks like you're running the installer from a containerized environment."
         m_echo "    > Flatpak support is ${BOLD}EXPERIMENTAL${RESET}!"
@@ -443,7 +446,7 @@ check_flatpak_env() {
 
 check_eft_running() {
     case $(pidof "BsgLauncher.exe") in
-        '') m_msg "${BOLD}${BLUE}OK${RESET}" ;;
+        '') m_success "OK" ;;
         *) m_err "Please close the BsgLauncher and the EFT client before installing (and playing) SPT!" ;;
     esac
 }
@@ -497,7 +500,7 @@ check_dependencies() {
     fi
 
     # Success
-    m_msg "${BOLD}${BLUE}OK${RESET}"
+    m_success "OK"
 }
 
 
@@ -549,7 +552,7 @@ check_disk_space() {
     && m_err "Not enough free disk space! ($free_gb available < $total_gb needed)"
 
     # Success
-    m_msg "${BOLD}${BLUE}OK${RESET} ($free_gb available > $total_gb needed)"
+    m_success "OK ($free_gb available > $total_gb needed)"
 }
 
 
@@ -578,7 +581,7 @@ check_mod_install_path() {
         m_err "SPT install directory not empty"
     fi
     # TODO: Check for weird paths passed to the installer
-    m_msg "${BOLD}${BLUE}OK${RESET} (Path: '${SPT_INSTALL_PATH}')"
+    m_success "OK (Path: '${SPT_INSTALL_PATH}')"
 }
 
 
@@ -594,14 +597,14 @@ verify_cached() {
     local filename=${cached_path##*/}
     m_msg "Checking for cached file '${filename}'"
     if [ -f "${cached_path}" ]; then
-        m_msg "${BLUE}Found '${filename}' in cache directory${RESET}"
+        m_success "Found '${filename}' in cache directory"
 
         # Check hash
         check_hash "${cached_path}" "${expected_hash}"; status=$?
 
         # Hash mismatch? Get rid of that sh*t
         if [ $status != 0 ]; then
-            m_warn "Removing cached file '${filename}'"
+            m_msg "Removing cached file '${filename}'"
             rm -f "${cached_path}" \
             || m_err "Failed to remove file '${filename}'"
             return 1
@@ -609,7 +612,7 @@ verify_cached() {
             return 0
         fi
     else
-        m_msg "${YELLOW}File not cached${RESET}"
+        m_warn "File not cached"
         return 1
     fi
 }
@@ -639,19 +642,42 @@ cp_eft_files() {
 }
 
 
-set_prefix() {
-    PREFIX_PATH="${1}"
-    # Make sure the given path exists & is a wine prefix
-    if [ ! -d "${PREFIX_PATH}" ] || [ ! -f "${PREFIX_PATH}/system.reg" ]; then
-        m_err "'${PREFIX_PATH}' is not a valid prefix directory"
+set_prefix_path() {
+    local absolute_path="${1:-"${SCRIPT_ROOT_PATH}"}"
+    # Check if the path is valid
+    if [ ! -f "${absolute_path}/system.reg" ]; then
+        m_warn "'${absolute_path}' is not a valid wine prefix directory"
     fi
+    # Update global variable
+    PREFIX_PATH="${absolute_path}"
 }
 
 
 set_spt_path() {
-    # Define SPT install path
-    SPT_RELATIVE_INSTALL_PATH="${1:-"${SPT_RELATIVE_INSTALL_PATH}"}"
-    SPT_INSTALL_PATH="${PREFIX_PATH%/}/${SPT_RELATIVE_INSTALL_PATH%/}"
+    local relative_path="${1:-${SPT_DEFAULT_INSTALL_PATH}}"
+    local absolute_path="${PREFIX_PATH%/}/${relative_path}"
+    # Check if the path is valid
+    if [[ "${absolute_path}" != *"drive_c"* ]]; then
+        m_err "The path must be installed inside the 'drive_c' directory"
+    elif [[ "${absolute_path}" != *"${PREFIX_PATH}"* ]]; then
+        m_err "The path must be inside the correct wine prefix directory"
+    fi
+    # Update global variable
+    SPT_INSTALL_PATH="${absolute_path}"
+}
+
+
+set_backup_path() {
+    local relative_path="${1:-${SPT_DEFAULT_BACKUP_PATH}}"
+    local absolute_path="${PREFIX_PATH%/}/${relative_path}"
+    # Check if the path is valid
+    if [[ "${absolute_path}" != *"drive_c"* ]]; then
+        m_err "The path must be inside the 'drive_c' directory"
+    elif [[ "${absolute_path}" != *"${PREFIX_PATH}"* ]]; then
+        m_err "The path must be inside the correct wine prefix directory"
+    fi
+    # Update global variable
+    SPT_BACKUP_PATH="${absolute_path}"
 }
 
 
@@ -659,7 +685,7 @@ validate_metadata() {
     local file_path="${1}"
     # Check if file exists, if not - fail the check
     [ ! -f "${file_path}" ] \
-    && m_msg "${YELLOW}File does not exist${RESET}" \
+    && m_warn "File does not exist" \
     && return 1
 
     # Calculate time elapsed since last modified
@@ -672,11 +698,11 @@ validate_metadata() {
 
     # If elapsed time >= TTL - fail the check
     [[ $elapsed -ge $ttl ]] \
-    && m_msg "${YELLOW}File is outdated${RESET}" \
+    && m_warn "File is outdated" \
     && return 1
 
     # Check passed
-    m_msg "${BLUE}File is valid${RESET}"
+    m_success "File is valid"
 }
 
 
@@ -802,18 +828,22 @@ opt_patcher() {
     # SUCCESS! ※\(^o^)/※
     if [ "${source_path}" == "${target_path}" ]; then
         m_msg "Cleaning up ..."
-        rm -rf "$source_path/SPT_Patches" 2>/dev/null || m_warn "Failed to remove 'SPT_Patches' directory"
-        rm -rf "$source_path/patcher.exe" 2>/dev/null || m_warn "Failed to remove 'patcher.exe'"
+        if [[ -d "${source_path}/SPT_Patches" ]]; then
+            rm -rf "${source_path}/SPT_Patches" || m_warn "Failed to remove 'SPT_Patches' directory"
+        fi
+        if [[ -f "${source_path}/patcher.exe" ]]; then
+            rm -rf "${source_path}/patcher.exe" || m_warn "Failed to remove 'patcher.exe'"
+        fi
     fi
     
-    m_msg "${BOLD}${BLUE}Done! ※\(^o^)/※${RESET}"
+    m_success "Done! ※\(^o^)/※"
 }
 
 
 opt_installer() {
     m_msg "Launching installer..."
     
-    set_prefix "${1:-"${PREFIX_PATH}"}"
+    set_prefix_path "${1}"
     set_spt_path "${2}"
 
     # Check EFT installation
@@ -838,7 +868,7 @@ opt_installer() {
     m_msg "Getting installed EFT version"
     INSTALLED_EFT_VERSION=$(get_installed_eft_version)
     [ $? != 0 ] && m_subshell_err "${INSTALLED_EFT_VERSION}"
-    m_msg "${BLUE}Found EFT version: '${INSTALLED_EFT_VERSION}'${RESET}"
+    m_success "Found EFT version: '${INSTALLED_EFT_VERSION}'"
 
     if [[ ${REINSTALL_SPT} -eq 1 ]]; then
         # Backup user files
@@ -924,7 +954,7 @@ opt_installer() {
 
         elif [[ "${PATCHER_TARGET_EFT_VERSION}" -eq "${INSTALLED_EFT_VERSION}" ]]; then
             # Downpatcher is compatible!
-            m_msg "${BLUE}Patcher is compatible with your installed EFT version${RESET}"
+            m_success "Patcher is compatible with your installed EFT version"
 
             # Check for cached patcher archive
             verify_cached "${PATCHER_FILE_PATH}" "${PATCHER_EXPECTED_HASH}"; status=$?
@@ -1045,8 +1075,6 @@ opt_backup() {
     # if no args given, restore all defined user data directories
     [ "$#" -eq 0 ] && dirs=("${SPT_USER_DATA_DIRS[@]}")
 
-    local absolute_root_path="${PREFIX_PATH%/}/${SPT_RELATIVE_ROOT_BACKUP_PATH%/}"
-
     # Get installed SPT version (if any)
     # TODO: Move to be able to use it somewhere else
     local core_json_file="${SPT_INSTALL_PATH}/SPT_Data/Server/configs/core.json"
@@ -1057,15 +1085,15 @@ opt_backup() {
     # Prepare backup directory
     printf -v timestamp '%(%Y%m%d-%H%M)T' -1
     local backup_name="spt-${INSTALLED_SPT_VERSION}-${timestamp}"
-    local absolute_backup_path="${absolute_root_path%/}/${backup_name%/}"
+    local backup_path="${SPT_BACKUP_PATH%/}/${backup_name%/}"
 
-    m_msg "Creating backup in '${absolute_backup_path}'"
+    m_msg "Creating backup in '${backup_path}'"
 
     # Copy required directories from the SPT install path to the backup path
     for dir in "${dirs[@]}"; do
         local source_path="${SPT_INSTALL_PATH%/}/${dir}"
-        local target_path="${absolute_backup_path}/${dir}"
-        local formatted="${source_path#*"${absolute_root_path}"/}"
+        local target_path="${backup_path}/${dir}"
+        local formatted="${source_path#*"${SPT_BACKUP_PATH}"/}"
         m_dbg "Backing up: ${formatted}"
             if [[ -d "${source_path}" ]]; then
                 m_cp "${source_path%/}/" "${target_path%/}/" \
@@ -1074,18 +1102,18 @@ opt_backup() {
         done
 
     # Final check if exists
-    [ ! -d "${absolute_backup_path}" ] \
-    && m_err "User backup directory at '${absolute_backup_path}' does not exist"
+    [ ! -d "${backup_path}" ] \
+    && m_err "User backup directory at '${backup_path}' does not exist"
 
     # Cache path to the latest backup
-    echo "${absolute_backup_path}" > "${CACHE_PATH}/latest_backup" \
+    echo "${backup_path}" > "${CACHE_PATH}/latest_backup" \
     || m_warn "Failed to create cache file '${SPT_LATEST_BACKUP_FILE}'"
 
     # Update global variable for the cached backup path
     get_cached_backup_path
 
     m_msg "A new backup has been successfully created at:"
-    m_echo "    > ${absolute_backup_path}"
+    m_echo "    > ${backup_path}"
 }
 
 
@@ -1103,7 +1131,7 @@ opt_restore() {
     # Check for spt install directory
     [ ! -d "${SPT_INSTALL_PATH}" ] \
     && m_err "SPT directory at '${SPT_INSTALL_PATH}' does not exist"
-    m_warn "${YELLOW}Restore triggered${RESET}"
+    m_echo "${YELLOW}Restore triggered${RESET}"
     m_echo
     m_echo "    > This command will attempt to restore the following files and/or directories:"
     m_echo "    > ${UNDERLINE}${dirs[*]}${RESET}"
@@ -1121,15 +1149,15 @@ opt_restore() {
     m_ask "Do you want to continue?"
 
     # Array of directories and files to restore
+    # TODO: Rework this to look for existing files in the source backup directory!
     for dir in "${dirs[@]}"; do
         local source_path="${CACHED_BACKUP_PATH%/}/${dir}"
         local target_path="${SPT_INSTALL_PATH%/}/${dir}"
         local formatted="${source_path#*"${CACHED_BACKUP_PATH}"/}"
-        m_dbg "Restoring: ${formatted}"
-        if [[ -d "${source_path}" ]]; then
-            m_cp "${source_path%/}/" "${target_path%/}/" \
-            || m_err "Failed to restore '${source_path}'"
-        else m_warn "File or directory '${source_path}' does not exist"; fi
+        if [[ -d "${source_path}" ]] then
+            m_msg "Restoring: ${formatted}"
+            m_cp "${source_path%/}/" "${target_path%/}/" || m_err "Failed to restore '${source_path}'"
+        fi
     done
 
     m_msg "All files have been restored successfully"
@@ -1140,7 +1168,7 @@ opt_self_update() {
     local script_path="${SCRIPT_ROOT_PATH}/${TITLE}"
 
     # Display warning for not fully implemented feature
-    m_warn "Not fully implemented yet"
+    m_echo "${YELLOW}Not fully implemented yet${RESET}"
     m_echo
     m_echo "    > The script will attempt to download the latest version available from here:"
     m_echo "    > ${UNDERLINE}${SCRIPT_UPDATE_URL}${RESET}"
@@ -1167,7 +1195,7 @@ opt_clear_cache() {
     fi
 
     # Prompt user
-    m_warn "Cache clearing triggered"
+    m_echo "${BOLD}${YELLOW}Cache clearing triggered${RESET}"
     m_echo
     m_echo "    > This action will remove ${BOLD}ALL${RESET} cached files in:"
     m_echo "    > ${UNDERLINE}${CACHE_PATH}${RESET}"
@@ -1184,7 +1212,7 @@ opt_clear_cache() {
 
 
 set_reinstall() {
-    m_msg "${YELLOW}Re-install mode for SPT enabled${RESET}"
+    m_echo "${BOLD}${YELLOW}Re-install mode for SPT enabled${RESET}"
     m_echo
     m_echo "    > This mode will backup the following files/directories:"
     m_echo "    > ${UNDERLINE}${SPT_USER_DATA_DIRS[*]}${RESET}"
@@ -1207,7 +1235,7 @@ set_debug() {
         '1') DEBUG_OUTPUT=$value;;
         '2') DEBUG_OUTPUT=$value;;
         *)
-            m_warn "Invalid setting used for 'set_debug' - defaulting to 1"
+            m_dbg "Invalid setting used for 'set_debug' - defaulting to 1"
             DEBUG_OUTPUT=1
         ;;
     esac
@@ -1220,30 +1248,10 @@ set_debug() {
 # Main entry #
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
 
-# Set default prefix path
-set_prefix "${SCRIPT_ROOT_PATH}"
-
-# Create directories (temp / cache)
-readonly TEMP_PATH="$(mktemp -d -t "${TITLE}.XXXXXXXXX")"
-[ ! -d "${TEMP_PATH}" ] && m_err "Failed to create temp directory"
-
-if [ ! -d "${CACHE_PATH}" ]; then
-    mkdir -p "${CACHE_PATH}" || m_err "Failed to create directory at '${CACHE_PATH}'"
-fi
-
-if [ ! -d "${BINARIES_PATH}" ]; then
-    mkdir "${BINARIES_PATH}" || m_err "Failed to create directory at '${BINARIES_PATH}'"
-fi
-
 # Remove old log, otherwise we just append more lines to it
-[ -f "${LOG_PATH}" ] && m_run rm -f "${LOG_PATH}" 2>/dev/null
-
-# Update global variable for the cached backup path
-get_cached_backup_path
-
-# Reserve first argument which always has to be the option command
-OPTION="${1}"
-shift 1
+if [[ -f "${LOG_PATH}" ]]; then
+    rm -f "${LOG_PATH}" || m_warn "Failed to remove old log file in '${LOG_PATH}'"
+fi
 
 # Apply launch arguments
 for arg in "$@"; do
@@ -1260,13 +1268,13 @@ for arg in "$@"; do
         ;;
         "--no-wait" | "-nw")
             # Ignore sleep times
-            m_echo " > Sleep times disabled"
+            m_dbg " > Sleep times disabled"
             NO_WAIT=1
             shift 1
         ;;
         "--no-prompt" | "-np")
             # Disabled user prompts
-            m_echo " > User prompts disabled"
+            m_dbg " > User prompts disabled"
             NO_PROMPT=1
             shift 1
         ;;
@@ -1277,36 +1285,68 @@ for arg in "$@"; do
     esac
 done
 
+# Create directories (temp / cache)
+readonly TEMP_PATH="$(mktemp -d -t "${TITLE}.XXXXXXXXX")"
+[ ! -d "${TEMP_PATH}" ] && m_err "Failed to create temp directory"
+
+if [ ! -d "${CACHE_PATH}" ]; then
+    mkdir -p "${CACHE_PATH}" || m_err "Failed to create directory at '${CACHE_PATH}'"
+fi
+
+if [ ! -d "${BINARIES_PATH}" ]; then
+    mkdir "${BINARIES_PATH}" || m_err "Failed to create directory at '${BINARIES_PATH}'"
+fi
+
+# Set default prefix path
+set_prefix_path
+
+# Set/update spt install path
+set_spt_path
+
+# Set/update backup path
+set_backup_path
+
+# Update global variable for the cached backup path
+get_cached_backup_path
+
+# Reserve first argument which always has to be the option command
+OPTION="${1}"
+shift 1
+
 # Apply launch option
 case $OPTION in
     "patch")
         opt_version
+        check_flatpak_env
         m_echo "A log file will be generated at:"
         m_echo "  ${BOLD}-> ${LOG_PATH}${RESET}"
         m_echo
         m_sleep
-        check_flatpak_env
         opt_patcher "$@"
     ;;
     "install")
         opt_version
+        check_flatpak_env
         m_echo "A log file will be generated at:"
         m_echo "  ${BOLD}-> ${LOG_PATH}${RESET}"
         m_echo
         m_sleep
-        check_flatpak_env
         opt_installer "$@"
     ;;
     "reinstall")
         set_reinstall || m_exit 3
-        opt_version && opt_installer "$@"
+        opt_version
+        check_flatpak_env
+        opt_installer "$@"
     ;;
     "backup")
-        # Create a new backup
+        opt_version
+        check_flatpak_env
         opt_backup "$@"
     ;;
     "restore")
-        # Restore a existing backup
+        opt_version
+        check_flatpak_env
         opt_restore "$@"
     ;;
     "")
