spt-additions: Improves SPT update code - Added more detailed manual update instructions if automated updates are not possible - Improve readability - Improve & simplify code

diff --git a/scripts/spt-additions b/scripts/spt-additions
--- a/scripts/spt-additions
+++ b/scripts/spt-additions
@@ -1101,23 +1101,13 @@ opt_update() {
     local option="$1" && shift
     case "${option}" in
         spt|sptarkov)
-            local installed_eft
-            local update_eft update_version update_url update_hash
+            local inst_eft inst_mod_eft inst_spt
+            local upd_eft upd_version upd_url upd_hash
             local major minor hotfix
 
-            # Check installed EFT
-            if ! check_eft_installed; then
-                warn "Escape from Tarkov is not installed"
-            fi
-            
-            installed_eft=$( get_product_version "${EFT_DIR}/EscapeFromTarkov.exe" | cut -d "." -f4 ) \
-            || err "Failed to get installed EFT version" "$?"
-
-            # Check installed SPT
-            if [[ -z "${SPT_DIR}" ]] || [[ ! -d "${SPT_DIR}" ]]; then
-                msg "SPTarkov is not installed"
-                m_exit 0
-            fi
+            # Check if EFT & SPT are installed
+            if ! check_eft_installed; then err "Escape from Tarkov is not installed"; fi
+            if [[ -z "${SPT_DIR}" ]] || [[ ! -d "${SPT_DIR}" ]]; then msg "SPTarkov is not installed" && m_exit 0; fi
 
             # Get required metadata for mod release
             if ! check_ttl "${MOD_JSON_PATH}"; then
@@ -1125,74 +1115,80 @@ opt_update() {
                 m_curl -s -L "${URL[mod-json]}" -o "${MOD_JSON_PATH}"
             fi
 
-            # - Check installed and available SPT version strings
-            installed_version=$( get_product_version "${SPT_DIR}/SPT/SPT.Server.exe" | cut -d "." -f1-3 ) \
-            || err "Failed to get installed SPT version" "$?"
+            # Get infos about the current SPT installation
+            inst_spt=$( get_product_version "${SPT_DIR}/SPT/SPT.Server.exe" ) || err "Failed to get installed SPT version" "$?"
+            inst_spt=$( echo "${inst_spt}" | cut -d "." -f1-3 )
+            inst_mod_eft=$( get_product_version "${SPT_DIR}/EscapeFromTarkov.exe" ) || err "Failed to get mod EFT version" "$?"
+            inst_mod_eft=$( echo "${inst_mod_eft}" | cut -d "." -f4 )
 
-            inst_major=$( echo "${installed_version}" | cut -d "." -f1 )
-            inst_minor=$( echo "${installed_version}" | cut -d "." -f2 )
-            inst_hotfix=$( echo "${installed_version}" | cut -d "." -f3 )
-
-            update_eft=$( jq -r '.ClientVersion' "${MOD_JSON_PATH}" ) || err "Failed to get required EFT version for SPT" "$?"
-            update_version=$( jq -r '.AkiVersion' "${MOD_JSON_PATH}" ) || err "Failed to get remote SPT version" "$?"
-            update_url=$( jq -r '.Mirrors[].DownloadUrl' "${MOD_JSON_PATH}" ) || err "Failed to get SPT download url" "$?"
-            update_hash=$( jq -r '.Mirrors[].Hash' "${MOD_JSON_PATH}" ) || err "Failed to get mod hash" "$?"
+            # Get infos about the latest SPT version
+            upd_eft=$( jq -r '.ClientVersion' "${MOD_JSON_PATH}" ) || err "Failed to get required EFT version for SPT" "$?"
+            upd_version=$( jq -r '.AkiVersion' "${MOD_JSON_PATH}" ) || err "Failed to get remote SPT version" "$?"
+            upd_url=$( jq -r '.Mirrors[].DownloadUrl' "${MOD_JSON_PATH}" ) || err "Failed to get SPT download url" "$?"
+            upd_hash=$( jq -r '.Mirrors[].Hash' "${MOD_JSON_PATH}" ) || err "Failed to get SPT archive hash" "$?"
             
-            upd_major=$( echo "${update_version}" | cut -d "." -f1 )
-            upd_minor=$( echo "${update_version}" | cut -d "." -f2 )
-            upd_hotfix=$( echo "${update_version}" | cut -d "." -f3 )
+            msg "Installed SPT version is \"${inst_spt}\""
+            msg "Latest SPT version is \"${upd_version}\""
 
-            msg "Installed SPT version is \"${installed_version}\""
-            msg "Latest SPT version is \"${update_version}\""
+            if [[ $( echo "${upd_version}" | cut -d "." -f1 ) -gt $( echo "${inst_spt}" | cut -d "." -f1 ) ]]; then major=1; fi
+            if [[ $( echo "${upd_version}" | cut -d "." -f2 ) -gt $( echo "${inst_spt}" | cut -d "." -f2 ) ]]; then minor=1; fi
+            if [[ $( echo "${upd_version}" | cut -d "." -f3 ) -gt $( echo "${inst_spt}" | cut -d "." -f3 ) ]]; then hotfix=1; fi
 
-            if [[ "${update_version}" == "${installed_version}" ]]; then
-                # Nothing to do, we are up-to-date!
-                msg "SPT is up-to-date." && m_exit 0
-            elif [[ "${installed_eft}" != "${update_eft}" ]]; then
-                # Incompatible EFT version
-                msg "${BOLD}${YELLOW}Incompatible EFT version found on your system!${RESET}"
-                msg "   > Installed: ${installed_eft}"
-                msg "   > Required: ${update_eft}"
-                msg "   > Please check out the release notes for this build & re-install SPT manually."
-                msg "   > ${BOLD}Release notes${RESET}: ${URL[spt-release]}/tag/${update_version}"
-                err "Incompatible EFT version"
-            elif [[ "${upd_major}" -gt "${inst_major}" ]]; then
-                msg "${BOLD}${YELLOW}Major SPT update detected!${RESET}"
-                msg "   > Please follow the install instructions found in the release notes"
-                msg "   > for this version & re-install SPT manually"
-                msg "   > ${BOLD}Release notes${RESET}: ${URL[spt-release]}/tag/${update_version}"
-                err "Major SPT update detected"
-            elif [[ "${upd_minor}" -gt "${inst_minor}" ]]; then
-                msg "${BOLD}${YELLOW}Minor SPT update detected!${RESET}"
-                msg "   > User profiles & mods might not be compatible."
-                msg "   > Please check out the release notes for this build & update / re-install SPT manually."
-                msg "   > ${BOLD}Release notes${RESET}: ${URL[spt-release]}/tag/${update_version}"
-                err "Minor SPT update detected"
-            elif [[ "${upd_hotfix}" -gt "${inst_hotfix}" ]]; then
-                msg "${BOLD}${YELLOW}A new update is available!${RESET}"
-                msg "   > ${BOLD}Release notes${RESET}: ${URL[spt-release]}/tag/${update_version}"
-                yesno "Do you want to install it?" || m_exit 0
-                msg "${BOLD}Updating SPT to version \"${update_version}\" ...${RESET}"
+            if [[ "${upd_version}" == "${inst_spt}" ]]; then
+                msg "${BOLD}SPT is up-to-date.${RESET}" && m_exit 0
+            elif [[ $major == 1 ]]; then
+                {   msg "${BOLD}${YELLOW}A new major release is available!${RESET}"
+                    msg "   > ${BOLD}${YELLOW}NOTE${RESET}: User profiles & mods usually are not compatible for major updates."
+                    msg
+                    msg "   ${BOLD}Please check out the release notes & re-install SPT manually:${RESET}"
+                    msg "   > ${URL[spt-release]}/tag/${upd_version}"
+                    msg
+                    msg "   1. Update the additions script with: ${BOLD}spt-additions self-update${RESET}"
+                    msg "   2. Backup or delete your old SPTarkov directory in \"${SPT_DIR}\""
+                    msg "   3. Update Escape from Tarkov inside the BSG Launcher"
+                    msg "   4. Re-install the latest SPT version with: ${BOLD}spt-additions install spt${RESET}"
+                } | more
+            elif [[ $minor == 1 ]]; then
+                {   msg "${BOLD}${YELLOW}A new minor release is available!${RESET}"
+                    msg "   > ${BOLD}${YELLOW}NOTE${RESET}: User profiles & mods might not be compatible."
+                    msg
+                    msg "   ${BOLD}Please check out the release notes & update / re-install SPT manually:${RESET}"
+                    msg "   > ${URL[spt-release]}/tag/${upd_version}"
+                    msg
+                    msg "   ${BOLD}How to update:${RESET}"
+                    msg "   1. Download the latest release archive: ${upd_url}"
+                    msg "   2. Extract its content into \"${SPT_DIR}\" & override when asked"
+                    msg
+                    msg "   ${BOLD}How to re-install:${RESET}"
+                    msg "   1. Backup or delete your old SPTarkov directory in \"${SPT_DIR}\""
+                    msg "   2. Update Escape from Tarkov inside the BSG Launcher"
+                    msg "   3. Re-install the latest SPT version with: ${BOLD}spt-additions install spt${RESET}"
+                }
+            elif [[ $hotfix == 1 ]]; then
+                {   msg "${BOLD}${YELLOW}A new hotfix release is available!${RESET}"
+                    msg "   ${BOLD}Please check out the release notes:${RESET}"
+                    msg "   > ${URL[spt-release]}/tag/${upd_version}"
+                    yesno "Do you want to install the update?" || m_exit 0
+                }
+                msg "${BOLD}Updating SPT to version \"${upd_version}\" ...${RESET}"
                 
                 # Check for cached mod archive
-                if ! check_cached "${MOD_PATH}" "${update_hash}"; then
-
+                if ! check_cached "${MOD_PATH}" "${upd_hash}"; then
                     # Download archive
                     msg "Downloading mod archive..."
-                    m_curl -L "${update_url}" -o "${MOD_PATH}"
+                    m_curl -L "${upd_url}" -o "${MOD_PATH}"
 
                     # Make sure the file is good to use
-                    check_hash "${MOD_PATH}" "${update_hash}" || err "File \"${MOD_PATH}\" is corrupted"
+                    check_hash "${MOD_PATH}" "${upd_hash}" || err "File \"${MOD_PATH}\" is corrupted"
                 fi
 
                 # Extract mod archive to install directory
                 msg "Extracting \"mod\" archive..."
                 m_7z "${MOD_PATH}" "${SPT_DIR}"
 
-                msg "${GREEN}Update successful!${RESET}"
+                msg "${GREEN}${BOLD}Update successful!${RESET}"
             else
-                # WTH did just happen?!
-                err "Unknown exception"
+                err "Unhandled exception"
             fi
         ;;
         additions|script) opt_selfupdate ;;
