spt-additions: More help page improvements & code clean up

diff --git a/scripts/spt-additions b/scripts/spt-additions
--- a/scripts/spt-additions
+++ b/scripts/spt-additions
@@ -977,97 +977,6 @@ uninstall_prefix() {
 #   Option functions  #
 # # # # # # # # # # # #
 
-opt_patch() {
-    msg "Patching game files..."
-    local files_total
-    local target_path="${1:-"${SPT_DIR}"}"
-    local source_path="${2:-"${target_path}"}"
-    target_path=$( realpath -m "${target_path%/}" )
-    source_path=$( realpath -m "${source_path%/}" )
-
-    # Fail if the target director does not exist
-    [[ -z "${target_path}" ]] && err "Target path is not set"
-    [[ ! -d "${target_path}" ]] && err "Target directory \"${target_path}\" does not exist"
-
-    # Make sure all native dependencies are installed
-    check_native_deps
-
-    # Search in optional SOURCE directory
-    if [ "$( find "${source_path}" -maxdepth 1 -type d -name "SPT_Patches" 2>/dev/null )" ]; then
-        source_path="${source_path}"
-    # Search in TARGET directory
-    elif [ "$( find "${target_path}" -maxdepth 1 -type d -name "SPT_Patches" 2>/dev/null )" ]; then
-        source_path="${target_path}"
-    else
-        err "Unable to locate \"SPT_Patches\" directory in \"${source_path}\""
-    fi
-
-    local progress=1
-    files_total=$( find "${source_path}/SPT_Patches" \( -type f -printf x \) | wc -c )
-
-    # Iterate files
-    echo; find "${source_path}/SPT_Patches" \( -type f \) -print0 | while IFS= read -r -d '' source; do 
-        local progress_string="[${progress}/${files_total}]"
-        # Isolate the operation extension
-        local extension="${source##*.}"
-        # Isolate sub-directories of SPT_Patches
-        local trimmed="${source#*SPT_Patches/}"
-        # Remove operation extension to get actual file name
-        trimmed="${trimmed%.*}"
-
-        local output="${target_path}/${trimmed}"
-        local target="${output}.decoded"
-        local dir_path="${output%/*}"
-
-        case "$extension" in
-            "delta")
-                msg -o "${progress_string} (*) Patching: ${trimmed##*/}"
-                hpatchz "${output}" "${source}" "${target}" >/dev/null 2>> "${LOG_PATH}" || return 1
-                # Remove old file and replace with .decoded file
-                [[ ! -f "${target}" ]] && return 1
-                rm "${output}" || return 1
-                m_mv "${target}" "${output}" || return 1
-            ;;
-            "del")
-                msg -o "${progress_string} (-) Deleting: ${trimmed##*/}"
-                rm "${output}" || return 1
-                if [[ -z "$( m_ls -A "${dir_path}" )" ]]; then
-                    msg -o "${progress_string} (-) Deleting directory: ${dir_path##*/}"
-                    rm -r "${dir_path}" || return 1
-                fi
-            ;;
-            "new")
-                msg -o "${progress_string} (+) Adding: ${trimmed##*/}"
-                if [[ ! -d "${dir_path}" ]]; then
-                    msg -o "${progress_string} (+) Adding directory: ${dir_path##*/}"
-                    m_mkdir "${dir_path}"
-                fi
-                cp "${source}" "${output}" || return 1
-            ;;
-            *)
-                return 1
-            ;;
-        esac
-        progress=$((progress+1))
-    done
-
-    local status=$?
-    if [[ "$status" -ne "0" ]]; then
-        # Failed patching
-        m_rm -r "${SPT_DIR}" && err "Failed to patch game files" $status
-    fi
-    
-    # Clean up patcher files
-    if [[ "${target_path}" == *"${source_path}"* ]]; then
-        msg "Cleaning up patch files..."
-        [[ -d "${source_path}/SPT_Patches" ]] && rm -r "${source_path}/SPT_Patches"
-        [[ -f "${source_path}/patcher.exe" ]] && rm -r "${source_path}/patcher.exe"
-    fi
-
-    msg "Done patching game files!"
-}
-
-
 opt_install() {
     # SYNTAX: spt-additions -p ~/Games/sptarkov install spt 
     local option="$1" && shift
@@ -1207,6 +1116,97 @@ opt_update() {
         "") err "Option \"update\" requires an argument" ;;
         *) err "Invalid option \"${option}\"" ;;
     esac
+}
+
+
+opt_patch() {
+    msg "Patching game files..."
+    local files_total
+    local target_path="${1:-"${SPT_DIR}"}"
+    local source_path="${2:-"${target_path}"}"
+    target_path=$( realpath -m "${target_path%/}" )
+    source_path=$( realpath -m "${source_path%/}" )
+
+    # Fail if the target director does not exist
+    [[ -z "${target_path}" ]] && err "Target path is not set"
+    [[ ! -d "${target_path}" ]] && err "Target directory \"${target_path}\" does not exist"
+
+    # Make sure all native dependencies are installed
+    check_native_deps
+
+    # Search in optional SOURCE directory
+    if [ "$( find "${source_path}" -maxdepth 1 -type d -name "SPT_Patches" 2>/dev/null )" ]; then
+        source_path="${source_path}"
+    # Search in TARGET directory
+    elif [ "$( find "${target_path}" -maxdepth 1 -type d -name "SPT_Patches" 2>/dev/null )" ]; then
+        source_path="${target_path}"
+    else
+        err "Unable to locate \"SPT_Patches\" directory in \"${source_path}\""
+    fi
+
+    local progress=1
+    files_total=$( find "${source_path}/SPT_Patches" \( -type f -printf x \) | wc -c )
+
+    # Iterate files
+    echo; find "${source_path}/SPT_Patches" \( -type f \) -print0 | while IFS= read -r -d '' source; do 
+        local progress_string="[${progress}/${files_total}]"
+        # Isolate the operation extension
+        local extension="${source##*.}"
+        # Isolate sub-directories of SPT_Patches
+        local trimmed="${source#*SPT_Patches/}"
+        # Remove operation extension to get actual file name
+        trimmed="${trimmed%.*}"
+
+        local output="${target_path}/${trimmed}"
+        local target="${output}.decoded"
+        local dir_path="${output%/*}"
+
+        case "$extension" in
+            "delta")
+                msg -o "${progress_string} (*) Patching: ${trimmed##*/}"
+                hpatchz "${output}" "${source}" "${target}" >/dev/null 2>> "${LOG_PATH}" || return 1
+                # Remove old file and replace with .decoded file
+                [[ ! -f "${target}" ]] && return 1
+                rm "${output}" || return 1
+                m_mv "${target}" "${output}" || return 1
+            ;;
+            "del")
+                msg -o "${progress_string} (-) Deleting: ${trimmed##*/}"
+                rm "${output}" || return 1
+                if [[ -z "$( m_ls -A "${dir_path}" )" ]]; then
+                    msg -o "${progress_string} (-) Deleting directory: ${dir_path##*/}"
+                    rm -r "${dir_path}" || return 1
+                fi
+            ;;
+            "new")
+                msg -o "${progress_string} (+) Adding: ${trimmed##*/}"
+                if [[ ! -d "${dir_path}" ]]; then
+                    msg -o "${progress_string} (+) Adding directory: ${dir_path##*/}"
+                    m_mkdir "${dir_path}"
+                fi
+                cp "${source}" "${output}" || return 1
+            ;;
+            *)
+                return 1
+            ;;
+        esac
+        progress=$((progress+1))
+    done
+
+    local status=$?
+    if [[ "$status" -ne "0" ]]; then
+        # Failed patching
+        m_rm -r "${SPT_DIR}" && err "Failed to patch game files" $status
+    fi
+    
+    # Clean up patcher files
+    if [[ "${target_path}" == *"${source_path}"* ]]; then
+        msg "Cleaning up patch files..."
+        [[ -d "${source_path}/SPT_Patches" ]] && rm -r "${source_path}/SPT_Patches"
+        [[ -f "${source_path}/patcher.exe" ]] && rm -r "${source_path}/patcher.exe"
+    fi
+
+    msg "Done patching game files!"
 }
 
 
@@ -1576,6 +1576,13 @@ opt_selfupdate() {
 }
 
 
+opt_version() {
+    msg "${BOLD}Version: ${RESET}${VERSION} (${DATE})"
+    local script_hash=$( get_hash "${SCRIPT_PATH}/${TITLE}" ) || err "Failed to get script hash"
+    msg "${BOLD}Hash: ${RESET}${script_hash}"
+}
+
+
 opt_help() {
     local option="${1}"
     case "${option}" in
@@ -1605,23 +1612,16 @@ opt_help() {
                 opt_help switches
             } | more
         ;;
-        self-install)
-            {   msg "Install this additions script to a local bin directory for ease of use"
+        patch)
+            {   msg "Downpatch EFT game files to a supported version for SPTarkov"
                 msg 
-            } | more
-        ;;
-        self-update)
-            {   msg "Update this additions script to the latest version"
+                msg "${BOLD}Usage:${RESET}"
+                msg "${YELLOW}$TITLE patch [target_path] [source_path]${RESET}"
                 msg
-            } | more
-        ;;
-        shortcut)
-            {   msg "${BOLD}Available options:${RESET}"
-                msg "eft|bsg|bsg-launcher           - Create/update BSG Launcher shortcut"
-                msg "launcher                       - Create/update SPT Launcher shortcut"
-                msg "server                         - Create/update SPT Server shortcut"
-                msg "spt|sptarkov                   - Create/update all SPT shortcuts"
-                msg "all                            - Create/update all available shortcuts"
+                msg "target_path - Destination install directory (defaults to \"${SPT_DIR}\")"
+                msg "source_path - Directory containing SPT_Patches (defaults to target_path)"
+                msg
+                msg "Example: ${YELLOW}$TITLE patch \"${SPT_DIR}\" \"~/Downloads/patcher\"${RESET}"
                 opt_help switches
             } | more
         ;;
@@ -1630,6 +1630,18 @@ opt_help() {
                 msg 
                 msg "${BOLD}Usage:${RESET}"
                 msg "${YELLOW}$TITLE [SWITCHES] run [eft|launcher|server|custom_command] [ARGS...]${RESET}"
+                msg
+                msg "${BOLD}Examples:${RESET}"
+                msg "${YELLOW}$TITLE run launcher${RESET}"
+                msg "${YELLOW}$TITLE run winecfg${RESET}"
+                msg "${YELLOW}$TITLE run winetricks [VERBS...]${RESET}"
+                msg "${YELLOW}$TITLE run ./custom.exe --example-arg${RESET}"
+                msg
+                msg "${BOLD}Available options:${RESET}"
+                msg "eft|bsg|bsg-launcher           - Run the BSG Launcher"
+                msg "launcher                       - Run the SPT Launcher"
+                msg "server                         - Run the SPT Server"
+                msg "custom_command                 - Run a custom command inside the prefix"
                 opt_help switches
             } | more
         ;;
@@ -1653,17 +1665,14 @@ opt_help() {
                 msg "list|-l                        - List all active environment variables"
                 opt_help switches
             } | more
-        ;;  
-        patch)
-            {   msg "Downpatch EFT game files to a supported version for SPTarkov"
-                msg 
-                msg "${BOLD}Usage:${RESET}"
-                msg "${YELLOW}$TITLE patch [target_path] [source_path]${RESET}"
-                msg
-                msg "target_path - Destination install directory (defaults to \"${SPT_DIR}\")"
-                msg "source_path - Directory containing SPT_Patches (defaults to target_path)"
-                msg
-                msg "Example: ${YELLOW}$TITLE patch \"${SPT_DIR}\" \"~/Downloads/patcher\"${RESET}"
+        ;;
+        shortcut)
+            {   msg "${BOLD}Available options:${RESET}"
+                msg "eft|bsg|bsg-launcher           - Create/update BSG Launcher shortcut"
+                msg "launcher                       - Create/update SPT Launcher shortcut"
+                msg "server                         - Create/update SPT Server shortcut"
+                msg "spt|sptarkov                   - Create/update all SPT shortcuts"
+                msg "all                            - Create/update all available shortcuts"
                 opt_help switches
             } | more
         ;;
@@ -1676,6 +1685,16 @@ opt_help() {
                 msg "data                           - Remove installer data files"
                 msg "all                            - Remove all of the above"
                 opt_help switches
+            } | more
+        ;;
+        self-install)
+            {   msg "Install this additions script to a local bin directory for ease of use"
+                msg 
+            } | more
+        ;;
+        self-update)
+            {   msg "Update this additions script to the latest version"
+                msg
             } | more
         ;;
         switches)
@@ -1715,13 +1734,6 @@ opt_help() {
         ;;
         *) msg "Invalid option: ${option}" ;;
     esac
-}
-
-
-opt_version() {
-    msg "${BOLD}Version: ${RESET}${VERSION} (${DATE})"
-    local script_hash=$( get_hash "${SCRIPT_PATH}/${TITLE}" ) || err "Failed to get script hash"
-    msg "${BOLD}Hash: ${RESET}${script_hash}"
 }
 
 
@@ -1784,11 +1796,11 @@ handle_opts() {
         install) opt_install "$@" ;;
         uninstall) opt_uninstall "$@" ;;
         update) opt_update "$@" ;;
+        patch) opt_patch "$@" ;;
         run) opt_run "$@" ;;
         dlloverride) opt_dlloverride "$@" ;;
-        patch) opt_patch "$@" ;;
-        shortcut) opt_shortcut "$@" ;;
         env) opt_env "$@" ;;
+        shortcut) opt_shortcut "$@" ;;
         clean) opt_clean "$@" ;;
         self-update) opt_selfupdate ;;
         self-install) opt_selfinstall ;;
