spt-additions: Add script hash retrieval and validation

diff --git a/scripts/spt-additions b/scripts/spt-additions
--- a/scripts/spt-additions
+++ b/scripts/spt-additions
@@ -21,7 +21,8 @@ shopt -s extglob
 trap int INT; int() { warn "Interrupt received" && m_exit; }
 
 TITLE="spt-additions"; AUTHOR="MadByte"; LICENSE="MIT"
-VERSION="0.8.2"; DATE="2025-10-17"
+VERSION="0.8.2"
+DATE="2025-10-17"
 
 # ANSI codes
 BOLD="\e[1m"; UNDERLINE="\e[2m"; RESET="\e[0m"
@@ -82,6 +83,7 @@ URL[spt-server-ico]="https://cdn2.steamgriddb.com/icon_thumb/9f7431ea593b8e57401
 # Metadata
 URL[patcher-json]="https://slugma.waffle-lord.net/mirrors.json"
 URL[mod-json]="https://spt-releases.modd.in/release.json"
+URL[script-hash]="https://raw.githubusercontent.com/MadByteDE/SPT-Linux-Guide/main/scripts/additions-hash.txt"
 
 # Links
 URL[spt-release]="https://github.com/sp-tarkov/build/releases"
@@ -368,6 +370,11 @@ get_env() {
 }
 
 
+get_hash() {
+    md5sum "$@" | cut -d ' ' -f 1 | xxd -r -p | base64 2>/dev/null
+}
+
+
 get_product_version() {
     local filepath="${1}"
     [[ ! -f "${filepath}" ]] && exit 11
@@ -559,8 +566,8 @@ check_hash() {
     [[ -z "${expected_hash}" ]] && err "Missing \"expected_hash\" argument"
     # use file to calculate MD5 hash and ENCODE in base64
     msg "Calculating checksum for file: \"${file_path##*/}\""
-    file_hash=$( md5sum "${file_path}" | cut -d ' ' -f 1 | xxd -r -p | base64 2>/dev/null )
-    [[ -z "${file_hash}" ]] && err "Failed to calculate hash"
+    file_hash=$( get_hash "${file_path}" ) || err "Failed to calculate hash"
+    [[ -z "${file_hash}" ]] && err "get_hash returned empty string"
     # Compare
     if [[ "${file_hash}" != "${expected_hash}" ]]; then
         warn "Hash check mismatch (File: \"${file_hash}\" != Expected: \"${expected_hash}\")"
@@ -1488,6 +1495,9 @@ opt_selfinstall() {
 
     # Search for bin paths in the PATH environment variable
     for path in "${bin_paths[@]}"; do
+        local remote_hash=$( curl -sf "${URL[script-hash]}" )
+        [[ -z "${remote_hash}" ]] && err "Failed to get remote script hash"
+        msg "${BOLD}Remote hash${RESET}:   ${remote_hash}"
         if [[ -z $( echo "${PATH}" | grep "${path}" ) ]]; then continue; fi
 
         # Found a user bin path
@@ -1497,11 +1507,15 @@ opt_selfinstall() {
 
         if [[ "$?" == 0 ]]; then
             [[ ! -d "${path}" ]] && m_mkdir "${path}"
-            msg "Downloading \"${TITLE}\"..."
-            cd "${path}" && m_curl -LO "${URL[installer-script]}"
-            m_chmod +x "${path}/${TITLE}"
-            msg "${GREEN}Successfully installed ${TITLE} into \"${path}\"!${RESET}"
-            msg "   > Run \"${YELLOW}${TITLE} -h${RESET}\" for more details."
+            msg "Downloading ${TITLE}..."
+            cd "${TMP_DIR}" && m_curl -sLO "${URL[installer-script]}"
+            if ! check_hash "${TMP_DIR}/${TITLE}" "${remote_hash}"; then
+                err "Downloaded script is corrupted"
+            fi
+            msg "Installing ${TITLE}..."
+            m_mv "${TMP_DIR}/${TITLE}" "${SCRIPT_PATH}/${TITLE}"
+            m_chmod +x "${SCRIPT_PATH}/${TITLE}"
+            msg "${GREEN}${BOLD}Done! ※\(^o^)/※${RESET}"
             installed=1
             return 0
         else
@@ -1512,17 +1526,31 @@ opt_selfinstall() {
 
 
 opt_selfupdate() {
-    if [[ "${NO_PROMPT}" != 1 ]]; then
-        msg "> ${BOLD}The script will attempt to download the latest version from:${RESET}"
-        msg "> ${UNDERLINE}${URL[installer-script]}${RESET}"
-        msg
-        msg "> This feature is ${BOLD}NOT${RESET} fully implemented yet & won't validate the new script file!"
-        msg
-        yesno "Do you want to continue?" || m_exit 0
+    local current_hash=$( get_hash "${SCRIPT_PATH}/${TITLE}" ) || err "Failed to get script hash"
+    local remote_hash=$( curl -sf "${URL[script-hash]}" )
+    [[ -z "${remote_hash}" ]] && err "Failed to get remote script hash"
+    msg "${BOLD}Current hash${RESET}:  ${current_hash}"
+    msg "${BOLD}Remote hash${RESET}:   ${remote_hash}"
+    if [[ "${current_hash}" == "${remote_hash}" ]]; then
+        msg "${BOLD}The script is up-to-date.${RESET}"
+        return 0
+    else
+        if [[ "${NO_PROMPT}" != 1 ]]; then
+            msg "> ${BOLD}The script will attempt to download the latest version from:${RESET}"
+            msg "> ${UNDERLINE}${URL[installer-script]}${RESET}"
+            msg
+            yesno "Do you want to continue?" || m_exit 0
+        fi
+        msg "Downloading ${TITLE}..."
+        cd "${TMP_DIR}" && m_curl -sLO "${URL[installer-script]}"
+        if ! check_hash "${TMP_DIR}/${TITLE}" "${remote_hash}"; then
+            err "Downloaded script is corrupted"
+        fi
+        msg "Installing ${TITLE}..."
+        m_mv "${TMP_DIR}/${TITLE}" "${SCRIPT_PATH}/${TITLE}"
+        m_chmod +x "${SCRIPT_PATH}/${TITLE}"
+        msg "${GREEN}${BOLD}Done! ※\(^o^)/※${RESET}"
     fi
-    msg "Updating ${TITLE}..."
-    cd "${SCRIPT_PATH}" && m_curl -s -LO "${URL[installer-script]}"
-    m_chmod +x "${SCRIPT_PATH}"
 }
 
 
@@ -1634,6 +1662,8 @@ opt_help() {
 
 opt_version() {
     msg "${BOLD}Version: ${RESET}${VERSION} (${DATE})"
+    local script_hash=$( get_hash "${SCRIPT_PATH}/${TITLE}" ) || err "Failed to get script hash"
+    msg "${BOLD}Hash: ${RESET}${script_hash}"
 }
 
 
