spt-additions: v0.6.7 - Added automated dependency install for 7zip - Minor code optimization - bump version

diff --git a/scripts/spt-additions b/scripts/spt-additions
--- a/scripts/spt-additions
+++ b/scripts/spt-additions
@@ -23,7 +23,7 @@ shopt -s extglob
 trap int INT; int() { err "Interrupt received"; }
 
 TITLE="spt-additions"; AUTHOR="MadByte"; LICENSE="MIT"
-VERSION="0.6.6-2"; DATE="2025-09-20"
+VERSION="0.6.7"; DATE="2025-09-20"
 
 # ANSI codes
 BOLD="\e[1m"; UNDERLINE="\e[2m"; RESET="\e[0m"
@@ -69,6 +69,7 @@ INSTALL_MODE="native"
 
 # Libraries / Tools
 URL[umu-launcher]="https://github.com/Open-Wine-Components/umu-launcher/releases/download/1.2.9/umu-launcher-1.2.9-zipapp.tar"
+URL[7zzs]="https://github.com/ip7z/7zip/releases/download/25.01/7z2501-linux-x64.tar.xz"
 URL[hpatchz]="https://github.com/sisong/HDiffPatch/releases/download/v4.11.1/hdiffpatch_v4.11.1_bin_linux64.zip"
 URL[jq]="https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-linux-amd64"
 URL[xxd]="http://ftp.de.debian.org/debian/pool/main/v/vim/xxd_9.1.1230-2_amd64.deb"
@@ -180,7 +181,7 @@ m_7z() {
     local archive_path="$(realpath -m "${1%/}")"; local target_path="$(realpath -m "${2%/}")"
     local filename="${archive_path##*/}"
     msg "Extracting \"${filename}\"..."
-    7z x -aoa "${archive_path}" -o"${target_path}" 1>/dev/null; local status=$?
+    7zzs x -aoa "${archive_path}" -o"${target_path}" 1>/dev/null; local status=$?
     [[ "$status" != 0 ]] && err "Failed to extract \"${filename}\" (status code $status)"
 }
 
@@ -608,13 +609,12 @@ check_aspnet() {
 
 check_native_deps() {
     local status
-    local cmds=( "7z" "xxd" "hpatchz" "jq" )
+    local cmds=( "7zzs" "xxd" "hpatchz" "jq" )
     msg "Checking for native dependencies..."
     for cmd in "${cmds[@]}"; do
         if ! command -v "${cmd}" &> /dev/null; then
             case ${cmd} in
-                jq|hpatchz|xxd) wrap_run install_dep "${cmd}" "${URL[${cmd}]}" || status=1 ;;
-                7z) warn "\"${cmd}\" is not installed on your system."; status=1 ;;
+                jq|hpatchz|xxd|7zzs) wrap_run install_dep "${cmd}" "${URL[${cmd}]}" || status=1 ;;
             esac
         fi
     done
@@ -699,21 +699,19 @@ check_ttl() {
 install_dep() {
     local cmd_name="$1"; local url="$2"
     local source_path="${3:-$TMP_DIR}"; local target_path="${4:-$RUNTIME_DIR}"
-    local download_name="${url##*/}"
-    [[ "$download_name" = *"."* ]] && local file_ext=".${download_name##*.}"
-    local file_name="${cmd_name}${file_ext}"
+    local filename="${url##*/}"
     cd "${TMP_DIR}" || err "Failed to change directory to \"$TMP_DIR\""
 
     # Download
-    msg "Downloading \"${cmd_name}\"..."
-    m_curl -s -L "${url}" -o "${file_name}"
+    msg "Downloading \"${filename}\"..."
+    m_curl -s -L "${url}" -o "${filename}"
 
     # Extract archive if needed
-    case "${file_ext}" in
-        *.zip*|*.7z*) m_7z "${file_name}" "${TMP_DIR}" ;;
-        *.tar*|*.zst*) tar -xf "${file_name}" || err "Failed to extract tar archive" ;;
+    case "${filename}" in
+        *.zip*|*.7z*) m_7z "${filename}" "${TMP_DIR}" ;;
+        *.tar*) tar -xf "${filename}" || err "Failed to extract tar archive" ;;
         *.deb*)
-            m_7z "${file_name}" "${TMP_DIR}"
+            m_7z "${filename}" "${TMP_DIR}"
             tar -xf "data.tar" || err "Failed to extract tar archive"
         ;;
         *) ;;
