spt-additions: v0.7.3 - Updated additions script url - Added support for new SPT file structure (symlink SPT.Launcher to root directory + updated launch-server script) - Minor log message string changes - bump version

diff --git a/scripts/spt-additions b/scripts/spt-additions
--- a/scripts/spt-additions
+++ b/scripts/spt-additions
@@ -21,7 +21,7 @@ shopt -s extglob
 trap int INT; int() { err "Interrupt received"; }
 
 TITLE="spt-additions"; AUTHOR="MadByte"; LICENSE="MIT"
-VERSION="0.7.2"; DATE="2025-10-05"
+VERSION="0.7.3"; DATE="2025-10-06"
 
 # ANSI codes
 BOLD="\e[1m"; UNDERLINE="\e[2m"; RESET="\e[0m"
@@ -76,7 +76,7 @@ URL[bsg-launcher]="https://prod.escapefromtarkov.com/launcher/download"
 URL[spt-installer]="https://ligma.waffle-lord.net/SPTInstaller.exe"
 
 # Scripts
-URL[installer-script]="https://raw.githubusercontent.com/MadByteDE/SPT-Linux-Guide/refs/heads/SPTv4-dev/scripts/spt-additions"
+URL[installer-script]="https://raw.githubusercontent.com/MadByteDE/SPT-Linux-Guide/main/scripts/spt-additions"
 
 # Icons
 URL[bsg-launcher-ico]="https://cdn2.steamgriddb.com/icon/33686c2d8930be81c843ffb7d4312605/32/256x256.png"
@@ -571,7 +571,7 @@ check_hash() {
     [[ ! -f "${file_path}" ]] && err "File \"${file_path}\" does not exist"
     [[ -z "${expected_hash}" ]] && err "Missing \"expected_hash\" argument"
     # use file to calculate MD5 hash and ENCODE in base64
-    msg "Calculating checksum: \"${file_path##*/}\""
+    msg "Calculating checksum for file: \"${file_path##*/}\""
     file_hash=$( md5sum "${file_path}" | cut -d ' ' -f 1 | xxd -r -p | base64 2>/dev/null )
     [[ -z "${file_hash}" ]] && err "Failed to calculate hash"
     # Compare
@@ -786,6 +786,9 @@ install_spt() {
     # Install server launch script
     install_launch_script
 
+    # Create launcher shortcut inside the root directory
+    ln -s "${SPT_DIR}/SPT/SPT.Launcher.exe" "${SPT_DIR}" || warn "Failed to create link for \"SPT.Launcher.exe\""
+
     case "${install_mode}" in
         native|proton)
             # Download icons to icons directory
@@ -926,8 +929,7 @@ m_run() {
 [[ $( m_run pidof "SPT.Server.Linux" ) != "" ]] && exit 0
 for term in "${terms[@]}"; do
     if m_run command -v $term &>/dev/null; then
-        cd "${root_path}"
-        m_run $term -e "./SPT.Server.Linux"
+        cd "${root_path}/SPT" && m_run $term -e "./SPT.Server.Linux"
     break
     fi
 done
